import { NetworkEvent } from "./INetwork";

/** Listener for events generated by Protocol.
 */
export interface ProtocolListener {
  onNetworkEvent(evt: NetworkEvent): void;
  onNetworkClosed(): void;
}

/** Protocol wraps around any network specific endpoints and
 * exposes a standardized interface using NetworkEvent to communicate with
 * the other layers of the server.
 */
export abstract class Protocol {
  protected mListener: ProtocolListener;
  public setListener(listener: ProtocolListener) {
    this.mListener = listener;
  }

  public abstract send(evt: NetworkEvent);
  public abstract getIdentity(): string;
  public abstract dispose(): void;
}
